"""Validate and collect evidence for WP-I0-006 without running build tools."""

from __future__ import annotations

import argparse
import copy
import csv
import hashlib
import json
import os
import pathlib
import re
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

sys.dont_write_bytecode = True

PACKAGE_ID = "WP-I0-006"
REQUIREMENT_ID = "CAN-MISSION-I0-005"
START_SHA = "82dfd9e8e2b3a826d5728cc3b2290b3aedb3e50c"
ROOT = pathlib.Path(__file__).resolve().parents[3]
GRAPHIFY = ROOT / "graphify"
PACKAGE_DIR = GRAPHIFY / "13-implementation" / PACKAGE_ID
DECISION_PATH = PACKAGE_DIR / "build-output-isolation-decision.json"
PRIOR_FAILED_INCIDENT_PATH = PACKAGE_DIR / "prior-failed-run-incident.md"
BASELINE_MANIFEST = GRAPHIFY / "13-implementation" / "WP-I0-001" / "sha256-manifest.csv"
PREREQUISITE_SUMMARY = GRAPHIFY / "13-implementation" / "WP-I0-001" / "package-summary.json"
PREREQUISITE_REVIEW = GRAPHIFY / "13-implementation" / "WP-I0-001" / "adversarial-review.md"
PACKET = GRAPHIFY / "12-semantic-implementation-plan" / "04-work-packages" / "packets" / f"{PACKAGE_ID}.md"
MEMBERSHIP = GRAPHIFY / "12-semantic-implementation-plan" / "04-work-packages" / "requirement-membership.csv"
DEPENDENCIES = GRAPHIFY / "12-semantic-implementation-plan" / "04-work-packages" / "dependencies.csv"
WORK_PACKAGES = GRAPHIFY / "12-semantic-implementation-plan" / "04-work-packages" / "work-packages.json"
TEST_MATRIX = GRAPHIFY / "12-semantic-implementation-plan" / "08-testing" / "work-package-test-matrix.csv"
WP_I0_001_GIT_REPORT = GRAPHIFY / "13-implementation" / "WP-I0-001" / "git-state-report.json"
WP_I0_005_VERIFICATION = GRAPHIFY / "13-implementation" / "WP-I0-005" / "verification-report.json"

sys.path.insert(0, str(GRAPHIFY / "tools"))
from write_guard import guard_write_path, write_json, write_text  # noqa: E402

EXPECTED_TOP_KEYS = {
    "schemaVersion",
    "packageId",
    "requirementIds",
    "decisionStatus",
    "decisionInvocation",
    "futureWorkspace",
    "forbiddenLocations",
    "forbiddenOperations",
    "failurePolicy",
}
OUTPUT_CLASSES = {"build", "test", "cache", "generated", "package-manager", "temporary"}
EXPECTED_ROOT_TEMPLATE = "${LAMHA_ISOLATED_OUTPUT_ROOT}/${PACKAGE_ID}/${RUN_ID}"
MAX_DECISION_BYTES = 64 * 1024
MAX_JSON_DEPTH = 64
MAX_JSON_NUMBER_CHARS = 128
EXPECTED_ALLOWED_WRITES = {
    "graphify/13-implementation/WP-I0-006/**",
    "Graphify final-certification artifacts regenerated by the existing certification tool",
}
EXPECTED_ROOT_CONSTRAINTS = {
    "resolved root is absolute and canonical",
    "resolved root is outside and not an ancestor of the Lamha repository",
    "resolved root is not a symlink, junction, or reparse point",
    "packageId and runId identify one authorized run",
    "the run root is empty or newly created when the authorized run begins",
    "no repository source tree is copied into the run root",
}
EXPECTED_FORBIDDEN_LOCATIONS = {
    "the Lamha repository root",
    "Codebase/** except separately authorized intentional source edits",
    "graphify/** except the current package evidence and existing certification outputs",
    ".git/**",
    "any parent or ancestor of the Lamha repository",
    "any unlisted external directory",
    "any symlink, junction, or reparse-point target",
}
EXPECTED_FORBIDDEN_OPERATIONS = {
    "clone",
    "git worktree creation",
    "repository copy",
    "repository archive",
    "repository backup",
    "unscoped build or test",
    "unscoped cache creation",
    "unscoped generated-code creation",
    "unscoped package-manager install",
    "silent fallback to an in-repository output path",
}
EXPECTED_INVOCATION_KEYS = {
    "outputExecutionAuthorized", "workspaceCreationAuthorized", "repositoryCopyAuthorized", "allowedWrites"
}
EXPECTED_FUTURE_KEYS = {
    "sourceWorkspace", "earliestPrerequisite", "separatePackageAuthorizationRequired",
    "authorizationMustName", "outputRootTemplate", "rootConstraints", "outputClassPaths", "commandRules",
}
EXPECTED_FAILURE_KEYS = {"behavior", "typedErrors", "partialCommitAllowed"}
EXPECTED_FAILURE_BEHAVIOR = "reject before command execution with a typed error and preserve authoritative state"
EXPECTED_SOURCE_WORKSPACE = "the existing Lamha repository checkout; never a clone, worktree, backup, archive, or duplicate source tree"
EXPECTED_AUTHORIZATION_FIELDS = {"packageId", "runId", "resolvedAbsoluteOutputRoot", "outputClasses", "commands"}
EXPECTED_COMMAND_RULES = {
    "Every output-producing command must belong to the separately authorized package and run.",
    "Every build, test, cache, generated, package-manager, and temporary path must resolve below its declared output-class path.",
    "Tool environment variables and command flags must redirect all writable outputs before execution.",
    "If a tool cannot prove complete redirection, that command is forbidden.",
    "Intentional source edits remain package-authorized source changes and must never be disguised as generated output.",
    "The invoking package must compare repository state before and after execution and report every unexpected path as failure.",
}
PORTABLE_RESERVED_NAMES = {
    "CON", "PRN", "AUX", "NUL", "CLOCK$",
    *(f"COM{index}" for index in range(1, 10)),
    *(f"LPT{index}" for index in range(1, 10)),
    "COM¹", "COM²", "COM³", "LPT¹", "LPT²", "LPT³",
}
ARTIFACT_SEGMENTS = {
    "workspace": {"workspace", "workspaces", ".worktree", ".worktrees"},
    "repositoryCopy": {"repository-copy", "repo-copy", "source-copy"},
    "build": {"build", "dist", "out", "target", ".next", ".svelte-kit"},
    "test": {"coverage", "test-results", "junit", "playwright-report", ".nyc_output"},
    "cache": {".cache", ".gradle", ".dart_tool", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", ".turbo"},
    "generatedCode": {"generated", "gen"},
    "packageManager": {"node_modules", ".pnpm-store", ".yarn", "pods"},
    "temporary": {"tmp", "temp"},
}
KNOWN_BASELINE_EMPTY_DIRECTORIES = {"Codebase/e2e/test-assets"}
EXPECTED_EVIDENCE_NAMES = {
    "build-output-isolation-decision.json",
    "collect_evidence.py",
    "artifact-scan.json",
    "completion-evidence.md",
    "package-summary.json",
    "provenance-report.json",
    "verification-report.json",
    "adversarial-review.md",
    "prior-failed-run-incident.md",
}
CERTIFICATION_PATHS = {
    "graphify/12-semantic-implementation-plan/12-validators/adversarial-results.json",
    "graphify/12-semantic-implementation-plan/13-reports/final-100-percent-certification.json",
    "graphify/12-semantic-implementation-plan/13-reports/final-content-manifest.json",
    "graphify/12-semantic-implementation-plan/13-reports/final-determinism-proof.json",
    "graphify/12-semantic-implementation-plan/13-reports/final-release-envelope.json",
    "graphify/12-semantic-implementation-plan/14-handoff/gpt-review-sha-manifest.json",
    "graphify/12-semantic-implementation-plan/PLAN-MANIFEST.json",
    "graphify/handoff-gpt/gpt-review-sha-manifest.json",
    "graphify/semantic-plan-source/reviews/final-100-percent-certification.json",
    "graphify/semantic-plan-source/reviews/final-content-manifest.json",
    "graphify/semantic-plan-source/reviews/final-determinism-proof.json",
    "graphify/semantic-plan-source/reviews/final-release-envelope.json",
}


@dataclass(frozen=True)
class DecisionError(Exception):
    code: str
    field: str
    message: str

    def as_dict(self) -> dict[str, str]:
        return {"status": "REJECTED", "code": self.code, "field": self.field, "message": self.message}


def reject(code: str, field: str, message: str) -> None:
    raise DecisionError(code, field, message)


def require_mapping(value: Any, field: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        reject("DECISION_FIELD_MISSING", field, "required object is missing or invalid")
    return value


def require_keys(value: dict[str, Any], required: set[str], field: str) -> None:
    missing = sorted(required - value.keys())
    if missing:
        reject("DECISION_FIELD_MISSING", field, f"missing keys: {', '.join(missing)}")


def require_exact_keys(value: dict[str, Any], expected: set[str], field: str) -> None:
    require_keys(value, expected, field)
    unexpected = sorted(value.keys() - expected)
    if unexpected:
        reject("DECISION_FIELD_UNEXPECTED", field, f"unexpected keys: {', '.join(unexpected)}")


def require_string_list(value: Any, field: str) -> list[str]:
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        reject("DECISION_FIELD_MISSING", field, "required string list is missing or invalid")
    return value


def require_exact_string_set(value: Any, expected: set[str], field: str, code: str) -> list[str]:
    items = require_string_list(value, field)
    if len(items) != len(expected) or set(items) != expected:
        reject(code, field, "values must match the exact approved set without duplicates")
    return items


def validate_decision(value: Any) -> dict[str, Any]:
    decision = require_mapping(value, "$" )
    require_exact_keys(decision, EXPECTED_TOP_KEYS, "$")
    if type(decision["schemaVersion"]) is not int or decision["schemaVersion"] != 1:
        reject("DECISION_FIELD_MISSING", "schemaVersion", "schemaVersion must equal 1")
    if not isinstance(decision["packageId"], str) or decision["packageId"] != PACKAGE_ID:
        reject("PACKAGE_ID_MISMATCH", "packageId", f"expected {PACKAGE_ID}")
    if require_string_list(decision["requirementIds"], "requirementIds") != [REQUIREMENT_ID]:
        reject("REQUIREMENT_ID_MISMATCH", "requirementIds", f"expected only {REQUIREMENT_ID}")
    if decision["decisionStatus"] != "DECISION_ONLY":
        reject("CURRENT_INVOCATION_OUTPUT_FORBIDDEN", "decisionStatus", "this package records a decision only")

    invocation = require_mapping(decision["decisionInvocation"], "decisionInvocation")
    require_exact_keys(invocation, EXPECTED_INVOCATION_KEYS, "decisionInvocation")
    if any(invocation[name] is not False for name in (
        "outputExecutionAuthorized", "workspaceCreationAuthorized", "repositoryCopyAuthorized"
    )):
        reject(
            "CURRENT_INVOCATION_OUTPUT_FORBIDDEN",
            "decisionInvocation",
            "current output execution, workspace creation, and repository copying must all be false",
        )
    require_exact_string_set(
        invocation["allowedWrites"], EXPECTED_ALLOWED_WRITES,
        "decisionInvocation.allowedWrites", "OUTPUT_ROOT_MUST_BE_EXTERNAL",
    )
    if set(invocation["allowedWrites"]) != EXPECTED_ALLOWED_WRITES:
        reject("OUTPUT_ROOT_MUST_BE_EXTERNAL", "decisionInvocation.allowedWrites", "only bounded Graphify evidence writes are allowed now")

    future = require_mapping(decision["futureWorkspace"], "futureWorkspace")
    require_exact_keys(future, EXPECTED_FUTURE_KEYS, "futureWorkspace")
    if future["separatePackageAuthorizationRequired"] is not True:
        reject("WORKSPACE_AUTHORIZATION_REQUIRED", "futureWorkspace.separatePackageAuthorizationRequired", "future execution needs separate package authorization")
    if future["earliestPrerequisite"] != "WP-I0-001 COMPLETE and GitHub-verified":
        reject("WORKSPACE_AUTHORIZATION_REQUIRED", "futureWorkspace.earliestPrerequisite", "verified WP-I0-001 completion is mandatory")
    require_exact_string_set(
        future["authorizationMustName"], EXPECTED_AUTHORIZATION_FIELDS,
        "futureWorkspace.authorizationMustName", "WORKSPACE_AUTHORIZATION_REQUIRED",
    )
    if future["outputRootTemplate"] != EXPECTED_ROOT_TEMPLATE:
        reject("OUTPUT_ROOT_TEMPLATE_INVALID", "futureWorkspace.outputRootTemplate", "the run-scoped external root template is invalid")
    if future["sourceWorkspace"] != EXPECTED_SOURCE_WORKSPACE:
        reject("DUPLICATE_TREE_FORBIDDEN", "futureWorkspace.sourceWorkspace", "the existing checkout must be used without a duplicate tree")
    require_exact_string_set(
        future["rootConstraints"], EXPECTED_ROOT_CONSTRAINTS,
        "futureWorkspace.rootConstraints", "OUTPUT_ROOT_MUST_BE_EXTERNAL",
    )
    class_paths = require_mapping(future["outputClassPaths"], "futureWorkspace.outputClassPaths")
    if set(class_paths) != OUTPUT_CLASSES:
        reject("OUTPUT_CLASS_SET_INVALID", "futureWorkspace.outputClassPaths", "every required output class must be mapped exactly once")
    for output_class, child in class_paths.items():
        invalid = (
            not isinstance(child, str)
            or not child
            or child.strip() != child
            or child in {".", ".."}
            or any(ord(character) < 32 or ord(character) == 127 for character in child)
            or bool(re.search(r'[<>:"/\\|?*]', child))
            or not bool(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}", child))
            or child.endswith((".", " "))
            or child.split(".", 1)[0].upper() in PORTABLE_RESERVED_NAMES
            or pathlib.PureWindowsPath(child).is_reserved()
        )
        if invalid:
            reject("OUTPUT_CHILD_INVALID", f"futureWorkspace.outputClassPaths.{output_class}", "output class path is not one portable safe child name")
    normalized_children = [child.casefold() for child in class_paths.values()]
    if len(set(normalized_children)) != len(OUTPUT_CLASSES):
        reject("OUTPUT_CHILD_INVALID", "futureWorkspace.outputClassPaths", "output class child names must be unique")
    require_exact_string_set(
        future["commandRules"], EXPECTED_COMMAND_RULES,
        "futureWorkspace.commandRules", "OUTPUT_ROOT_MUST_BE_EXTERNAL",
    )

    require_exact_string_set(
        decision["forbiddenLocations"], EXPECTED_FORBIDDEN_LOCATIONS,
        "forbiddenLocations", "OUTPUT_ROOT_MUST_BE_EXTERNAL",
    )
    require_exact_string_set(
        decision["forbiddenOperations"], EXPECTED_FORBIDDEN_OPERATIONS,
        "forbiddenOperations", "DUPLICATE_TREE_FORBIDDEN",
    )
    failure = require_mapping(decision["failurePolicy"], "failurePolicy")
    require_exact_keys(failure, EXPECTED_FAILURE_KEYS, "failurePolicy")
    if failure["behavior"] != EXPECTED_FAILURE_BEHAVIOR:
        reject("CURRENT_INVOCATION_OUTPUT_FORBIDDEN", "failurePolicy.behavior", "failure must reject before execution and preserve state")
    if failure["partialCommitAllowed"] is not False:
        reject("CURRENT_INVOCATION_OUTPUT_FORBIDDEN", "failurePolicy.partialCommitAllowed", "partial commit must be false")
    required_codes = {
        "DECISION_FIELD_MISSING", "DECISION_FIELD_UNEXPECTED", "DECISION_JSON_DUPLICATE_KEY",
        "DECISION_JSON_INVALID", "DECISION_JSON_NONSTANDARD_CONSTANT", "PACKAGE_ID_MISMATCH",
        "REQUIREMENT_ID_MISMATCH", "CURRENT_INVOCATION_OUTPUT_FORBIDDEN",
        "WORKSPACE_AUTHORIZATION_REQUIRED", "OUTPUT_ROOT_TEMPLATE_INVALID",
        "OUTPUT_ROOT_MUST_BE_EXTERNAL", "OUTPUT_CLASS_SET_INVALID", "OUTPUT_CHILD_INVALID",
        "DUPLICATE_TREE_FORBIDDEN",
    }
    require_exact_string_set(
        failure["typedErrors"], required_codes,
        "failurePolicy.typedErrors", "DECISION_FIELD_MISSING",
    )
    return {"status": "VALID", "packageId": PACKAGE_ID, "requirementId": REQUIREMENT_ID}


def strict_json_loads(text: str) -> Any:
    try:
        encoded_size = len(text.encode("utf-8"))
    except UnicodeError:
        reject("DECISION_JSON_INVALID", "$", "decision JSON contains an invalid Unicode scalar")
    if encoded_size > MAX_DECISION_BYTES:
        reject("DECISION_JSON_INVALID", "$", f"decision JSON exceeds {MAX_DECISION_BYTES} bytes")

    depth = 0
    in_string = False
    escaped = False
    for character in text:
        if in_string:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
        elif character == '"':
            in_string = True
        elif character in "[{":
            depth += 1
            if depth > MAX_JSON_DEPTH:
                reject("DECISION_JSON_INVALID", "$", f"decision JSON exceeds nesting depth {MAX_JSON_DEPTH}")
        elif character in "]}":
            depth -= 1

    def pairs_hook(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        value: dict[str, Any] = {}
        for key, item in pairs:
            if key in value:
                reject("DECISION_JSON_DUPLICATE_KEY", key, f"duplicate JSON member rejected: {key}")
            value[key] = item
        return value

    def parse_constant(value: str) -> None:
        reject("DECISION_JSON_NONSTANDARD_CONSTANT", "$", f"nonstandard JSON constant rejected: {value}")

    def parse_int(value: str) -> int:
        if len(value) > MAX_JSON_NUMBER_CHARS:
            reject("DECISION_JSON_INVALID", "$", "JSON integer exceeds the numeric limit")
        return int(value)

    def parse_float(value: str) -> float:
        if len(value) > MAX_JSON_NUMBER_CHARS:
            reject("DECISION_JSON_INVALID", "$", "JSON number exceeds the numeric limit")
        return float(value)

    try:
        return json.loads(
            text,
            object_pairs_hook=pairs_hook,
            parse_constant=parse_constant,
            parse_int=parse_int,
            parse_float=parse_float,
        )
    except DecisionError:
        raise
    except json.JSONDecodeError as error:
        reject("DECISION_JSON_INVALID", f"$:{error.lineno}:{error.colno}", "malformed JSON rejected")
    except (RecursionError, ValueError, OverflowError):
        reject("DECISION_JSON_INVALID", "$", "decision JSON exceeded parser limits")


def decode_json_bytes(data: bytes) -> str:
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        reject("DECISION_JSON_INVALID", "$", "decision JSON must be valid UTF-8")


def read_json_text(path: pathlib.Path) -> str:
    try:
        return decode_json_bytes(path.read_bytes())
    except DecisionError:
        raise
    except OSError:
        reject("DECISION_JSON_INVALID", str(path), "decision JSON is unavailable")


def strict_json_load_bytes(data: bytes) -> Any:
    if len(data) > MAX_DECISION_BYTES:
        reject("DECISION_JSON_INVALID", "$", f"decision JSON exceeds {MAX_DECISION_BYTES} bytes")
    return strict_json_loads(decode_json_bytes(data))


def load_json(path: pathlib.Path) -> Any:
    return json.loads(read_json_text(path))


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def run_git(*args: str) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env["GIT_OPTIONAL_LOCKS"] = "0"
    return subprocess.run(
        ["git", *args], cwd=ROOT, env=env, text=True, encoding="utf-8", errors="replace",
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False,
    )


def git_output(*args: str) -> str:
    result = run_git(*args)
    if result.returncode:
        raise RuntimeError(f"git {' '.join(args)} failed ({result.returncode}): {result.stderr.strip()}")
    return result.stdout.strip()


def status_paths(status: str) -> list[str]:
    paths: list[str] = []
    for line in status.splitlines():
        path = line[3:]
        if " -> " in path:
            path = path.split(" -> ", 1)[1]
        paths.append(path.replace("\\", "/"))
    return paths


def is_reparse(stat_result: os.stat_result, path: pathlib.Path) -> bool:
    return path.is_symlink() or bool(getattr(stat_result, "st_file_attributes", 0) & 0x400)


def recursive_inventory(base: pathlib.Path) -> dict[str, Any]:
    files: dict[str, pathlib.Path] = {}
    directories: list[str] = []
    reparses: list[str] = []
    special: list[str] = []
    stack = [base]
    while stack:
        directory = stack.pop()
        with os.scandir(directory) as entries:
            for entry in entries:
                path = pathlib.Path(entry.path)
                relative = path.relative_to(ROOT).as_posix()
                stat_result = entry.stat(follow_symlinks=False)
                if entry.is_symlink() or is_reparse(stat_result, path):
                    reparses.append(relative)
                elif entry.is_dir(follow_symlinks=False):
                    directories.append(relative)
                    stack.append(path)
                elif entry.is_file(follow_symlinks=False):
                    files[relative] = path
                else:
                    special.append(relative)
    return {
        "files": files,
        "directories": sorted(directories),
        "reparsePaths": sorted(reparses),
        "specialPaths": sorted(special),
    }


def classify_artifacts(paths: list[str]) -> dict[str, list[str]]:
    matches = {name: [] for name in ARTIFACT_SEGMENTS}
    for raw_path in sorted(set(paths)):
        segments = {segment.casefold() for segment in pathlib.PurePosixPath(raw_path.replace("\\", "/")).parts}
        for artifact_class, markers in ARTIFACT_SEGMENTS.items():
            if segments & {marker.casefold() for marker in markers}:
                matches[artifact_class].append(raw_path)
        if ".git" in segments and raw_path.replace("\\", "/").strip("/") != ".git":
            matches["repositoryCopy"].append(raw_path)
    return {name: sorted(set(class_paths)) for name, class_paths in matches.items()}


def artifact_classifier_fixtures() -> dict[str, Any]:
    fixtures = {
        "workspace": "graphify/13-implementation/WP-I0-006/workspace/run",
        "repositoryCopy": "graphify/13-implementation/WP-I0-006/repo-copy/Codebase",
        "build": "graphify/13-implementation/WP-I0-006/nested/build/output.bin",
        "test": "graphify/13-implementation/WP-I0-006/nested/coverage/result.json",
        "cache": "graphify/13-implementation/WP-I0-006/nested/__pycache__/value.pyc",
        "generatedCode": "graphify/13-implementation/WP-I0-006/nested/generated/value.rs",
        "packageManager": "graphify/13-implementation/WP-I0-006/nested/node_modules/pkg/index.js",
        "temporary": "graphify/13-implementation/WP-I0-006/nested/temp/value.tmp",
    }
    outcomes = []
    for expected_class, path in fixtures.items():
        actual = classify_artifacts([path])
        matched = sorted(name for name, values in actual.items() if values)
        outcomes.append({
            "path": path,
            "expectedClass": expected_class,
            "actualClasses": matched,
            "result": "PASS" if expected_class in matched else "FAIL",
        })
    safe_path = f"graphify/13-implementation/{PACKAGE_ID}/verification-report.json"
    safe_actual = classify_artifacts([safe_path])
    safe_matched = sorted(name for name, values in safe_actual.items() if values)
    outcomes.append({"path": safe_path, "expectedClass": None, "actualClasses": safe_matched, "result": "PASS" if not safe_matched else "FAIL"})
    return {"cases": outcomes, "result": "PASS" if all(item["result"] == "PASS" for item in outcomes) else "FAIL"}


def expected_parent_directories(paths: set[str]) -> set[str]:
    directories: set[str] = set()
    for raw_path in paths:
        parent = pathlib.PurePosixPath(raw_path).parent
        while parent.as_posix() not in {".", "Codebase"}:
            directories.add(parent.as_posix())
            parent = parent.parent
    return directories


def codebase_comparison() -> dict[str, Any]:
    expected: dict[str, tuple[int, str]] = {}
    with BASELINE_MANIFEST.open(encoding="utf-8", newline="") as stream:
        for row in csv.DictReader(stream):
            expected[row["path"]] = (int(row["size"]), row["sha256"])
    inventory = recursive_inventory(ROOT / "Codebase")
    current_paths: dict[str, pathlib.Path] = inventory["files"]
    added = sorted(current_paths.keys() - expected.keys())
    removed = sorted(expected.keys() - current_paths.keys())
    modified: list[str] = []
    for relative in sorted(current_paths.keys() & expected.keys()):
        path = current_paths[relative]
        size, digest = expected[relative]
        if path.stat().st_size != size or sha256_file(path) != digest:
            modified.append(relative)
    baseline_directories = expected_parent_directories(set(expected))
    unrepresented_directories = sorted(set(inventory["directories"]) - baseline_directories)
    baseline_directory_evidence = {
        "Codebase/e2e/test-assets": (
            "e2e/test-assets" in WP_I0_001_GIT_REPORT.read_text(encoding="utf-8")
            and "Codebase/e2e/test-assets" in WP_I0_005_VERIFICATION.read_text(encoding="utf-8")
        )
    }
    verified_baseline_empty = {
        path for path in KNOWN_BASELINE_EMPTY_DIRECTORIES if baseline_directory_evidence.get(path) is True
    }
    unexpected_directories = sorted(set(unrepresented_directories) - verified_baseline_empty)
    artifact_matches = classify_artifacts(added + unexpected_directories + inventory["reparsePaths"] + inventory["specialPaths"])
    artifact_count = sum(len(paths) for paths in artifact_matches.values())
    result = "PASS" if not (
        added or removed or modified or unexpected_directories or inventory["reparsePaths"] or inventory["specialPaths"] or artifact_count
    ) else "FAIL"
    return {
        "baselinePackage": "WP-I0-001",
        "baselineManifest": BASELINE_MANIFEST.relative_to(GRAPHIFY).as_posix(),
        "expectedFiles": len(expected),
        "currentFiles": len(current_paths),
        "added": added,
        "removed": removed,
        "modified": modified,
        "currentDirectories": len(inventory["directories"]),
        "baselineRepresentedDirectories": len(baseline_directories),
        "unrepresentedDirectories": unrepresented_directories,
        "verifiedBaselineEmptyDirectories": sorted(verified_baseline_empty),
        "baselineEmptyDirectoryEvidence": baseline_directory_evidence,
        "unexpectedDirectories": unexpected_directories,
        "reparsePaths": inventory["reparsePaths"],
        "specialPaths": inventory["specialPaths"],
        "artifactMatchesFromBaselineDelta": artifact_matches,
        "result": result,
    }


def repository_fingerprint() -> dict[str, Any]:
    status = git_output("status", "--porcelain=v1", "--untracked-files=all")
    comparison = codebase_comparison()
    value = {
        "head": git_output("rev-parse", "HEAD"),
        "status": status,
        "codebaseComparison": comparison,
    }
    value["sha256"] = hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")).hexdigest()
    return value


def probe_cases(valid: dict[str, Any]) -> dict[str, tuple[dict[str, Any], str]]:
    cases: dict[str, tuple[dict[str, Any], str]] = {}
    value = copy.deepcopy(valid)
    del value["futureWorkspace"]["outputRootTemplate"]
    cases["missing_field"] = (value, "DECISION_FIELD_MISSING")
    value = copy.deepcopy(valid)
    value["decisionInvocation"]["outputExecutionAuthorized"] = True
    cases["current_activation"] = (value, "CURRENT_INVOCATION_OUTPUT_FORBIDDEN")
    value = copy.deepcopy(valid)
    value["futureWorkspace"]["separatePackageAuthorizationRequired"] = False
    cases["missing_authorization"] = (value, "WORKSPACE_AUTHORIZATION_REQUIRED")
    value = copy.deepcopy(valid)
    value["futureWorkspace"]["rootConstraints"] = [
        item for item in value["futureWorkspace"]["rootConstraints"] if "outside and not an ancestor" not in item
    ]
    cases["repository_overlap"] = (value, "OUTPUT_ROOT_MUST_BE_EXTERNAL")
    value = copy.deepcopy(valid)
    value["futureWorkspace"]["outputClassPaths"].pop("test")
    cases["unmapped_output"] = (value, "OUTPUT_CLASS_SET_INVALID")
    value = copy.deepcopy(valid)
    value["futureWorkspace"]["outputClassPaths"]["test"] = "../test"
    cases["traversal_child"] = (value, "OUTPUT_CHILD_INVALID")
    value = copy.deepcopy(valid)
    value["forbiddenOperations"].remove("repository copy")
    cases["duplicate_tree"] = (value, "DUPLICATE_TREE_FORBIDDEN")
    value = copy.deepcopy(valid)
    value["forbiddenOperations"] = 7
    cases["malformed_type"] = (value, "DECISION_FIELD_MISSING")
    value = copy.deepcopy(valid)
    value["decisionInvocation"]["buildNowDespiteFalseFlags"] = True
    cases["unexpected_nested_authorization"] = (value, "DECISION_FIELD_UNEXPECTED")
    value = copy.deepcopy(valid)
    value["failurePolicy"]["behavior"] = "execute commands, write partial evidence, then reject"
    cases["contradictory_failure_behavior"] = (value, "CURRENT_INVOCATION_OUTPUT_FORBIDDEN")
    for name, child in (
        ("reserved_child", "CON"),
        ("alternate_stream_child", "test:alternate-stream"),
        ("whitespace_child", "   "),
        ("trailing_dot_child", "test."),
        ("control_child", "test\u0001"),
    ):
        value = copy.deepcopy(valid)
        value["futureWorkspace"]["outputClassPaths"]["test"] = child
        cases[name] = (value, "OUTPUT_CHILD_INVALID")
    value = copy.deepcopy(valid)
    value["futureWorkspace"]["outputClassPaths"]["test"] = "BUILD"
    cases["casefold_child_collision"] = (value, "OUTPUT_CHILD_INVALID")
    value = copy.deepcopy(valid)
    value["futureWorkspace"]["commandRules"].append("Commands may silently write all outputs inside Codebase.")
    cases["contradictory_extra_rule"] = (value, "OUTPUT_ROOT_MUST_BE_EXTERNAL")
    value = copy.deepcopy(valid)
    value["schemaVersion"] = True
    cases["boolean_schema_version"] = (value, "DECISION_FIELD_MISSING")
    value = copy.deepcopy(valid)
    value["futureWorkspace"]["sourceWorkspace"] = f"clone the repository now; {EXPECTED_SOURCE_WORKSPACE}"
    cases["contradictory_source_workspace"] = (value, "DUPLICATE_TREE_FORBIDDEN")
    value = copy.deepcopy(valid)
    value["futureWorkspace"]["unexpected"] = "allow writes"
    cases["unexpected_future_field"] = (value, "DECISION_FIELD_UNEXPECTED")
    value = copy.deepcopy(valid)
    value["failurePolicy"]["unexpected"] = "partial commit"
    cases["unexpected_failure_field"] = (value, "DECISION_FIELD_UNEXPECTED")
    for name, child in (
        ("overlong_child", "x" * 300),
        ("surrogate_child", "x\ud800"),
        ("bidi_override_child", "safe\u202etxt"),
    ):
        value = copy.deepcopy(valid)
        value["futureWorkspace"]["outputClassPaths"]["test"] = child
        cases[name] = (value, "OUTPUT_CHILD_INVALID")
    return cases


def raw_probe_cases(valid_text: str) -> dict[str, tuple[str | bytes, str]]:
    duplicate = valid_text.replace(
        '"outputExecutionAuthorized": false,',
        '"outputExecutionAuthorized": true,\n      "outputExecutionAuthorized": false,',
        1,
    )
    malformed = valid_text.rstrip()[:-1]
    nonstandard = valid_text.replace('"schemaVersion": 1', '"schemaVersion": NaN', 1)
    return {
        "raw_duplicate_authorization_key": (duplicate, "DECISION_JSON_DUPLICATE_KEY"),
        "raw_malformed_json": (malformed, "DECISION_JSON_INVALID"),
        "raw_nonstandard_constant": (nonstandard, "DECISION_JSON_NONSTANDARD_CONSTANT"),
        "raw_invalid_utf8": (b'{"schemaVersion":"\xff"}', "DECISION_JSON_INVALID"),
        "raw_excessive_nesting": ("[" * 2000 + "0" + "]" * 2000, "DECISION_JSON_INVALID"),
        "raw_oversized_integer": ("{\"schemaVersion\":" + "9" * 5000 + "}", "DECISION_JSON_INVALID"),
        "raw_oversized_document": ("{\"value\":\"" + "x" * (MAX_DECISION_BYTES + 1) + "\"}", "DECISION_JSON_INVALID"),
    }


def run_negative_probes(decision: dict[str, Any], decision_text: str) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    for name, (candidate, expected_code) in probe_cases(decision).items():
        try:
            validate_decision(candidate)
            results.append({"name": name, "expectedCode": expected_code, "actualCode": None, "result": "FAIL"})
        except DecisionError as error:
            results.append({
                "name": name, "expectedCode": expected_code, "actualCode": error.code,
                "field": error.field, "result": "PASS" if error.code == expected_code else "FAIL",
            })
    for name, (candidate_text, expected_code) in raw_probe_cases(decision_text).items():
        try:
            parsed = strict_json_load_bytes(candidate_text) if isinstance(candidate_text, bytes) else strict_json_loads(candidate_text)
            validate_decision(parsed)
            results.append({"name": name, "boundary": "raw-json", "expectedCode": expected_code, "actualCode": None, "result": "FAIL"})
        except DecisionError as error:
            results.append({
                "name": name, "boundary": "raw-json", "expectedCode": expected_code,
                "actualCode": error.code, "field": error.field,
                "result": "PASS" if error.code == expected_code else "FAIL",
            })
    return results


def authority_checks() -> dict[str, Any]:
    packet_text = PACKET.read_text(encoding="utf-8")
    membership_rows = list(csv.DictReader(MEMBERSHIP.open(encoding="utf-8", newline="")))
    dependency_rows = list(csv.DictReader(DEPENDENCIES.open(encoding="utf-8", newline="")))
    packages = load_json(WORK_PACKAGES)
    test_rows = list(csv.DictReader(TEST_MATRIX.open(encoding="utf-8", newline="")))
    package = next((item for item in packages if item["work_package_id"] == PACKAGE_ID), None)
    membership = [row for row in membership_rows if row["work_package_id"] == PACKAGE_ID]
    dependencies = [row for row in dependency_rows if row["work_package_id"] == PACKAGE_ID]
    tests = [row for row in test_rows if row["work_package_id"] == PACKAGE_ID]
    prerequisite_summary = load_json(PREREQUISITE_SUMMARY)
    prerequisite_review = PREREQUISITE_REVIEW.read_text(encoding="utf-8")
    checks = {
        "packetNamesPackage": f"# {PACKAGE_ID}" in packet_text,
        "packetNamesRequirement": REQUIREMENT_ID in packet_text,
        "registryPackageMatches": bool(package and package["included_requirement_ids"] == [REQUIREMENT_ID] and package["status"] == "NOT_STARTED"),
        "membershipMatches": len(membership) == 1 and membership[0]["canonical_id"] == REQUIREMENT_ID,
        "dependencyMatches": len(dependencies) == 1 and dependencies[0]["prerequisite_work_package_id"] == "WP-I0-001",
        "testMatrixMatches": len(tests) == 1 and REQUIREMENT_ID in tests[0]["failure_cases"],
        "prerequisiteSummaryPass": prerequisite_summary.get("status") == "PASS" and not prerequisite_summary.get("failures"),
        "prerequisiteExitGatePass": all(item.get("result") == "PASS" for item in prerequisite_summary.get("exitGateClauses", [])),
        "prerequisiteCompleteAndGitHubVerified": "Final package status: COMPLETE and GitHub-verified" in prerequisite_review,
        "contractsOwned": 0,
        "schemasOwned": 0,
        "componentsOwned": 0,
    }
    checks["result"] = "PASS" if all(value is True or value == 0 for key, value in checks.items() if key != "result") else "FAIL"
    return checks


def artifact_scan(codebase: dict[str, Any]) -> dict[str, Any]:
    status = git_output("status", "--porcelain=v1", "--untracked-files=all")
    paths = status_paths(status)
    outside_graphify = [path for path in paths if not path.startswith("graphify/")]
    unauthorized_graphify = [
        path for path in paths
        if path.startswith("graphify/")
        and not path.startswith(f"graphify/13-implementation/{PACKAGE_ID}/")
        and path not in CERTIFICATION_PATHS
    ]
    package_inventory = recursive_inventory(PACKAGE_DIR)
    expected_package_files = {f"graphify/13-implementation/{PACKAGE_ID}/{name}" for name in EXPECTED_EVIDENCE_NAMES}
    unexpected_package_files = sorted(set(package_inventory["files"]) - expected_package_files)
    unexpected_package_entries = sorted(
        unexpected_package_files
        + package_inventory["directories"]
        + package_inventory["reparsePaths"]
        + package_inventory["specialPaths"]
    )
    graphify_inventory = recursive_inventory(GRAPHIFY)
    agents_inventory = recursive_inventory(ROOT / ".agents")
    tracked_graphify_files = set(git_output("ls-tree", "-r", "--name-only", "HEAD", "graphify").splitlines())
    tracked_graphify_directories = expected_parent_directories(tracked_graphify_files)
    allowed_untracked_directories = {f"graphify/13-implementation/{PACKAGE_ID}"}
    unexpected_graphify_directories = sorted(
        set(graphify_inventory["directories"]) - tracked_graphify_directories - allowed_untracked_directories
    )
    ignored_untracked = sorted(
        line.replace("\\", "/")
        for line in git_output("ls-files", "--others", "--ignored", "--exclude-standard", "--directory").splitlines()
        if line
    )
    top_level = sorted(path.name for path in ROOT.iterdir())
    unexpected_top_level = sorted(set(top_level) - {".agents", ".git", "Codebase", "graphify"})
    isolated_env = os.environ.get("LAMHA_ISOLATED_OUTPUT_ROOT")
    classification_inputs = (
        codebase["added"]
        + codebase["unexpectedDirectories"]
        + codebase["reparsePaths"]
        + codebase["specialPaths"]
        + outside_graphify
        + unexpected_package_entries
        + unexpected_graphify_directories
        + graphify_inventory["reparsePaths"]
        + graphify_inventory["specialPaths"]
        + list(agents_inventory["files"])
        + agents_inventory["directories"]
        + agents_inventory["reparsePaths"]
        + agents_inventory["specialPaths"]
        + ignored_untracked
        + unexpected_top_level
    )
    forbidden_paths = classify_artifacts(classification_inputs)
    forbidden_counts = {name: len(class_paths) for name, class_paths in forbidden_paths.items()}
    classifier_fixtures = artifact_classifier_fixtures()
    return {
        "packageId": PACKAGE_ID,
        "gitStatusPaths": paths,
        "outsideGraphifyChanges": outside_graphify,
        "unauthorizedGraphifyChangesAtCollection": unauthorized_graphify,
        "unexpectedPackageFiles": unexpected_package_files,
        "unexpectedPackageEntries": unexpected_package_entries,
        "unexpectedGraphifyDirectories": unexpected_graphify_directories,
        "ignoredUntrackedPaths": ignored_untracked,
        "recursiveInventory": {
            "packageFiles": len(package_inventory["files"]),
            "packageDirectories": len(package_inventory["directories"]),
            "packageReparsePaths": package_inventory["reparsePaths"],
            "packageSpecialPaths": package_inventory["specialPaths"],
            "codebaseFiles": codebase["currentFiles"],
            "codebaseDirectories": codebase["currentDirectories"],
            "codebaseReparsePaths": codebase["reparsePaths"],
            "codebaseSpecialPaths": codebase["specialPaths"],
            "graphifyFiles": len(graphify_inventory["files"]),
            "graphifyDirectories": len(graphify_inventory["directories"]),
            "graphifyReparsePaths": graphify_inventory["reparsePaths"],
            "graphifySpecialPaths": graphify_inventory["specialPaths"],
            "agentsFiles": len(agents_inventory["files"]),
            "agentsDirectories": len(agents_inventory["directories"]),
            "agentsReparsePaths": agents_inventory["reparsePaths"],
            "agentsSpecialPaths": agents_inventory["specialPaths"],
        },
        "topLevelEntries": top_level,
        "unexpectedTopLevelEntries": unexpected_top_level,
        "isolatedOutputRootEnvironmentBound": isolated_env is not None,
        "codebaseComparison": codebase,
        "forbiddenArtifactClasses": forbidden_counts,
        "forbiddenArtifactPaths": forbidden_paths,
        "classifierFixtures": classifier_fixtures,
        "result": "PASS" if not (
            outside_graphify or unauthorized_graphify or unexpected_package_entries or unexpected_graphify_directories
            or graphify_inventory["reparsePaths"] or graphify_inventory["specialPaths"] or ignored_untracked or unexpected_top_level
            or agents_inventory["files"] or agents_inventory["directories"] or agents_inventory["reparsePaths"] or agents_inventory["specialPaths"]
            or isolated_env is not None or codebase["result"] != "PASS" or sum(forbidden_counts.values())
            or classifier_fixtures["result"] != "PASS"
        ) else "FAIL",
    }


def collect() -> int:
    started = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    failures: list[str] = []
    prior_failed_incident_recorded = PRIOR_FAILED_INCIDENT_PATH.exists()
    try:
        decision_text = read_json_text(DECISION_PATH)
    except DecisionError as error:
        decision_text = ""
        focused = error.as_dict()
        failures.append(f"decision validation: {error.code} at {error.field}")
    decision: dict[str, Any] | None = None
    if decision_text:
        try:
            decision = strict_json_loads(decision_text)
            focused = validate_decision(decision)
        except DecisionError as error:
            focused = error.as_dict()
            failures.append(f"decision validation: {error.code} at {error.field}")

    before_negative = repository_fingerprint()
    negative = run_negative_probes(decision, decision_text) if decision is not None and focused.get("status") == "VALID" else []
    after_negative = repository_fingerprint()
    codebase = after_negative["codebaseComparison"]
    if any(item["result"] != "PASS" for item in negative):
        failures.append("one or more negative probes did not return the expected typed error")
    if before_negative != after_negative:
        failures.append("negative validation changed repository state")

    authority = authority_checks()
    if authority["result"] != "PASS":
        failures.append("canonical package, membership, DAG, test, or prerequisite authority mismatch")
    if codebase["result"] != "PASS":
        failures.append("Codebase differs from the verified WP-I0-001 SHA-256 baseline")
    artifacts = artifact_scan(codebase)
    if artifacts["result"] != "PASS":
        failures.append("artifact scan found an unauthorized or output-producing path")

    verification = {
        "packageId": PACKAGE_ID,
        "requirementId": REQUIREMENT_ID,
        "collectionWindowUtc": {"start": started, "end": datetime.now(timezone.utc).replace(microsecond=0).isoformat()},
        "focusedValidation": {"decision": focused, "result": "PASS" if focused.get("status") == "VALID" else "FAIL"},
        "negativeValidation": {
            "probes": negative,
            "repositoryFingerprintBefore": before_negative,
            "repositoryFingerprintAfter": after_negative,
            "statePreserved": before_negative == after_negative,
            "result": "PASS" if negative and all(item["result"] == "PASS" for item in negative) and before_negative == after_negative else "FAIL",
        },
        "regressionValidation": {
            "authority": authority,
            "codebaseComparison": codebase,
            "result": "PASS" if authority["result"] == "PASS" and codebase["result"] == "PASS" else "FAIL",
        },
        "commandPolicy": {
            "commandsExecutedByCollector": ["read decision and authority", "read-only git inspection", "SHA-256 compare Codebase to WP-I0-001 baseline", "pure in-memory negative probes"],
            "buildCommands": 0,
            "testCommandsThatRunProductCode": 0,
            "packageManagerCommands": 0,
            "networkCommands": 0,
            "workspaceOrCopyCommands": 0,
        },
        "failureRecovery": "Decision validation is pure. Invalid candidates return typed errors before any command or write; before/after repository fingerprints are identical.",
    }
    exit_clauses = [
        {
            "clause": "The later writable boundary is explicit",
            "evidence": "The decision requires a separately authorized, run-scoped absolute output root outside the repository and maps all six output classes to unique children.",
            "result": "PASS" if focused.get("status") == "VALID" else "FAIL",
        },
        {
            "clause": "No workspace, repository copy, build, test, cache, generated-code, package-manager, or temporary output was created",
            "evidence": "The isolated output environment is unbound; output execution and workspace creation are false; the recursive artifact scan reports zero forbidden classes and zero outside-Graphify changes for this invocation.",
            "result": "PASS" if artifacts["result"] == "PASS" else "FAIL",
        },
        {
            "clause": "Invalid input returns typed errors with no partial authoritative state",
            "evidence": f"All {len(negative)} invalid decisions returned their expected typed errors and the before/after repository fingerprints match.",
            "result": "PASS" if negative and all(item["result"] == "PASS" for item in negative) and before_negative == after_negative else "FAIL",
        },
        {
            "clause": "The verified read-only provenance baseline remains intact",
            "evidence": f"All {codebase['currentFiles']} Codebase files match the WP-I0-001 path, size, and SHA-256 manifest; WP-I0-001 status and exit gate remain PASS.",
            "result": "PASS" if authority["result"] == "PASS" and codebase["result"] == "PASS" else "FAIL",
        },
    ]
    if any(item["result"] != "PASS" for item in exit_clauses):
        failures.append("one or more exit-gate clauses failed")
    verification["exitGateClauses"] = exit_clauses
    verification["priorFailedInvocation"] = {
        "recorded": prior_failed_incident_recorded,
        "evidencePath": f"13-implementation/{PACKAGE_ID}/prior-failed-run-incident.md" if prior_failed_incident_recorded else None,
        "effectOnCurrentInvocation": "history only; current invocation is independently validated" if prior_failed_incident_recorded else None,
    }
    verification["result"] = "PASS" if not failures else "FAIL"

    package_summary = {
        "packageId": PACKAGE_ID,
        "status": "PASS" if not failures else "FAIL",
        "failures": failures,
        "collectionWindowUtc": verification["collectionWindowUtc"],
        "checks": {
            "decisionValidation": verification["focusedValidation"]["result"],
            "negativeValidation": verification["negativeValidation"]["result"],
            "regressionValidation": verification["regressionValidation"]["result"],
            "artifactScan": artifacts["result"],
            "exitGate": "PASS" if all(item["result"] == "PASS" for item in exit_clauses) else "FAIL",
        },
        "counts": {
            "ownedRequirements": 1,
            "futureOutputClasses": len(OUTPUT_CLASSES),
            "negativeProbes": len(negative),
            "codebaseFilesVerified": codebase["currentFiles"],
            "forbiddenArtifacts": sum(artifacts["forbiddenArtifactClasses"].values()),
        },
        "evidenceFiles": [
            f"13-implementation/{PACKAGE_ID}/artifact-scan.json",
            f"13-implementation/{PACKAGE_ID}/build-output-isolation-decision.json",
            f"13-implementation/{PACKAGE_ID}/completion-evidence.md",
            f"13-implementation/{PACKAGE_ID}/prior-failed-run-incident.md",
            f"13-implementation/{PACKAGE_ID}/package-summary.json",
            f"13-implementation/{PACKAGE_ID}/provenance-report.json",
            f"13-implementation/{PACKAGE_ID}/verification-report.json",
        ],
        "exitGateClauses": exit_clauses,
    }
    provenance = {
        "packageId": PACKAGE_ID,
        "startingSha": START_SHA,
        "startingRemoteSha": START_SHA,
        "packetPath": PACKET.relative_to(GRAPHIFY).as_posix(),
        "packetSha256": sha256_file(PACKET),
        "ownedRequirements": [REQUIREMENT_ID],
        "prerequisites": [{"packageId": "WP-I0-001", "type": "REQUIRES_PROVENANCE", "status": "COMPLETE_AND_GITHUB_VERIFIED"}],
        "selection": {
            "rule": "exactly one explicit authorized package remained READY",
            "authorizationRecord": "13-implementation/WP-I0-005/adversarial-review.md",
            "readySet": [
                "WP-I0-006", "WP-I0-007", "WP-I0-008", "WP-I0-009", "WP-I0-010", "WP-I0-011",
                "WP-I1-001", "WP-I2-001", "WP-I2-002", "WP-I10-003", "WP-I15-006",
            ],
        },
        "scope": {
            "authorizedWrites": sorted(EXPECTED_ALLOWED_WRITES),
            "readOnly": ["Codebase/**", "graphify planning authority", "prior implementation evidence", ".git metadata via optional-lock-free reads"],
            "prohibited": ["all application files", "all current output roots", "repository clone/copy/worktree/archive/backup", "next-package implementation"],
        },
        "contractsOwned": [],
        "schemasOwned": [],
        "componentsOwned": [],
        "writeBoundary": f"graphify/13-implementation/{PACKAGE_ID}/** through graphify/tools/write_guard.py; existing final-certification tooling may regenerate its bounded Graphify outputs",
    }
    incident_section = """
## Prior failed invocation

`prior-failed-run-incident.md` preserves the previous invocation's disclosed external stdout-capture failure. That run was not committed or certified. This invocation streams validation output and is evaluated independently.
""" if prior_failed_incident_recorded else ""
    completion = f"""# {PACKAGE_ID} completion evidence

- Package: {PACKAGE_ID} — Build-output isolation decision
- Requirement: `{REQUIREMENT_ID}`
- Starting SHA: `{START_SHA}`
- Selection: the sole explicit authorization, independently confirmed READY from the canonical DAG.
- Files changed by the package: the decision, validator/collector, and evidence in this directory; existing Graphify certification outputs may be regenerated by the repository's certification tool.

## Requirement trace

`{REQUIREMENT_ID}` → `build-output-isolation-decision.json` → decision validation plus {len(negative)} typed negative probes → `verification-report.json` → four exit-gate clauses.

The decision authorizes no output-producing action now. A later package must separately authorize one run-scoped absolute root outside the repository, map build/test/cache/generated/package-manager/temporary outputs below it, redirect every tool write, and reject the command if complete redirection cannot be proven. The existing checkout is the source workspace; cloning, worktrees, backups, archives, and duplicate trees are forbidden.

## Validation

- Focused: **{verification['focusedValidation']['result']}** — decision structure and all boundary invariants validated.
- Negative: **{verification['negativeValidation']['result']}** — {len(negative)}/{len(negative)} invalid decisions produced the expected typed error; state fingerprint preserved.
- Regression: **{verification['regressionValidation']['result']}** — WP-I0-001 remains COMPLETE/PASS and {codebase['currentFiles']} Codebase files match its SHA-256 baseline.
- Artifact scan: **{artifacts['result']}** — zero current workspace/copy/build/test/cache/generated/package-manager artifacts and zero outside-Graphify changes.

{incident_section}

## Exit gate

""" + "\n".join(f"- **{item['result']}** — {item['clause']}: {item['evidence']}" for item in exit_clauses)

    write_json(PACKAGE_DIR / "artifact-scan.json", artifacts)
    write_json(PACKAGE_DIR / "verification-report.json", verification)
    write_json(PACKAGE_DIR / "package-summary.json", package_summary)
    write_json(PACKAGE_DIR / "provenance-report.json", provenance)
    write_text(PACKAGE_DIR / "completion-evidence.md", completion)
    print(json.dumps({"packageId": PACKAGE_ID, "status": package_summary["status"], "failures": failures}, indent=2))
    return 0 if not failures else 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--validate-only", action="store_true", help="validate the committed decision without writing evidence")
    parser.add_argument("--self-test", action="store_true", help="run valid and invalid in-memory cases without writing evidence")
    parser.add_argument("--negative-probe", help="run one invalid in-memory or raw-JSON case")
    args = parser.parse_args()
    try:
        decision_text = read_json_text(DECISION_PATH)
        decision = strict_json_loads(decision_text)
    except DecisionError as error:
        print(json.dumps(error.as_dict(), indent=2))
        return 1
    if args.negative_probe:
        structured = probe_cases(decision)
        raw = raw_probe_cases(decision_text)
        if args.negative_probe not in structured and args.negative_probe not in raw:
            print(json.dumps({"status": "UNKNOWN_NEGATIVE_PROBE", "name": args.negative_probe}, indent=2))
            return 3
        try:
            if args.negative_probe in structured:
                candidate, expected = structured[args.negative_probe]
                validate_decision(candidate)
            else:
                candidate_text, expected = raw[args.negative_probe]
                parsed = strict_json_load_bytes(candidate_text) if isinstance(candidate_text, bytes) else strict_json_loads(candidate_text)
                validate_decision(parsed)
        except DecisionError as error:
            print(json.dumps(error.as_dict(), indent=2))
            return 2 if error.code == expected else 3
        print(json.dumps({"status": "INVALID_TEST_FAILURE", "expectedCode": expected}, indent=2))
        return 3
    if args.validate_only:
        try:
            print(json.dumps(validate_decision(decision), indent=2))
            return 0
        except DecisionError as error:
            print(json.dumps(error.as_dict(), indent=2))
            return 1
    if args.self_test:
        try:
            valid = validate_decision(decision)
        except DecisionError as error:
            print(json.dumps(error.as_dict(), indent=2))
            return 1
        probes = run_negative_probes(decision, decision_text)
        result = {"valid": valid, "negativeProbes": probes, "stateWrites": 0}
        print(json.dumps(result, indent=2))
        return 0 if all(item["result"] == "PASS" for item in probes) else 1
    return collect()


if __name__ == "__main__":
    raise SystemExit(main())
