PRAGMA foreign_keys = ON;
CREATE TABLE schema_migration(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL, checksum TEXT NOT NULL);
CREATE TABLE rebuild_source(entity TEXT PRIMARY KEY, source_kind TEXT NOT NULL CHECK(source_kind IN ('AUTHORITATIVE_FILES','MEDIA_AND_SIDECARS','CACHE_ONLY','OPERATIONAL_JOURNAL','TEMPORARY_TRANSACTION_AUTHORITY')), description TEXT NOT NULL);
CREATE TABLE root_index(id TEXT PRIMARY KEY, path TEXT NOT NULL UNIQUE, revision INTEGER NOT NULL, access_mode TEXT NOT NULL, drive_id TEXT, state TEXT NOT NULL);
CREATE TABLE drive_index(id TEXT PRIMARY KEY, platform_identity TEXT NOT NULL UNIQUE, label TEXT NOT NULL, state TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE asset_identity_index(id TEXT PRIMARY KEY, content_hash TEXT NOT NULL, hash_algorithm TEXT NOT NULL, file_identity TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE asset_index(id TEXT PRIMARY KEY, identity_id TEXT NOT NULL REFERENCES asset_identity_index(id), root_id TEXT NOT NULL REFERENCES root_index(id), relative_path TEXT NOT NULL, media_type TEXT NOT NULL, captured_at TEXT, duration_ms INTEGER, revision INTEGER NOT NULL, sidecar_revision INTEGER, UNIQUE(root_id, relative_path));
CREATE TABLE companion_index(asset_id TEXT NOT NULL REFERENCES asset_index(id) ON DELETE CASCADE, companion_asset_id TEXT NOT NULL REFERENCES asset_index(id), companion_kind TEXT NOT NULL, PRIMARY KEY(asset_id, companion_asset_id));
CREATE TABLE metadata_index(asset_id TEXT PRIMARY KEY REFERENCES asset_index(id) ON DELETE CASCADE, camera_make TEXT, camera_model TEXT, lens TEXT, width INTEGER, height INTEGER, latitude REAL, longitude REAL, ocr_text TEXT, authoritative_revision INTEGER NOT NULL);
CREATE TABLE event_index(id TEXT PRIMARY KEY, title TEXT NOT NULL, start_at TEXT NOT NULL, end_at TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE event_asset_index(event_id TEXT NOT NULL REFERENCES event_index(id) ON DELETE CASCADE, asset_id TEXT NOT NULL REFERENCES asset_index(id) ON DELETE CASCADE, role TEXT NOT NULL, PRIMARY KEY(event_id, asset_id));
CREATE TABLE person_index(id TEXT PRIMARY KEY, canonical_name TEXT NOT NULL, hidden INTEGER NOT NULL DEFAULT 0, revision INTEGER NOT NULL);
CREATE TABLE person_alias_index(person_id TEXT NOT NULL REFERENCES person_index(id) ON DELETE CASCADE, alias TEXT NOT NULL, PRIMARY KEY(person_id, alias));
CREATE TABLE face_candidate_index(id TEXT PRIMARY KEY, asset_id TEXT NOT NULL REFERENCES asset_index(id) ON DELETE CASCADE, person_id TEXT REFERENCES person_index(id), status TEXT NOT NULL, confidence REAL, box_json TEXT NOT NULL, model_fingerprint TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE group_index(id TEXT PRIMARY KEY, canonical_name TEXT NOT NULL, parent_group_id TEXT REFERENCES group_index(id), revision INTEGER NOT NULL);
CREATE TABLE group_membership_index(id TEXT PRIMARY KEY, group_id TEXT NOT NULL REFERENCES group_index(id) ON DELETE CASCADE, person_id TEXT NOT NULL REFERENCES person_index(id) ON DELETE CASCADE, effective_from TEXT NOT NULL, effective_to TEXT, revision INTEGER NOT NULL);
CREATE TABLE relationship_index(id TEXT PRIMARY KEY, from_person_id TEXT NOT NULL REFERENCES person_index(id), to_person_id TEXT NOT NULL REFERENCES person_index(id), relationship_type TEXT NOT NULL, certainty REAL NOT NULL, effective_from TEXT, effective_to TEXT, revision INTEGER NOT NULL);
CREATE TABLE relationship_history_index(id TEXT PRIMARY KEY, relationship_id TEXT NOT NULL REFERENCES relationship_index(id) ON DELETE CASCADE, sequence INTEGER NOT NULL, payload_json TEXT NOT NULL, UNIQUE(relationship_id, sequence));
CREATE TABLE tag_index(id TEXT PRIMARY KEY, namespace TEXT NOT NULL, name TEXT NOT NULL, parent_tag_id TEXT REFERENCES tag_index(id), revision INTEGER NOT NULL, UNIQUE(namespace, name));
CREATE TABLE asset_tag_index(asset_id TEXT NOT NULL REFERENCES asset_index(id) ON DELETE CASCADE, tag_id TEXT NOT NULL REFERENCES tag_index(id) ON DELETE CASCADE, provenance TEXT NOT NULL, PRIMARY KEY(asset_id, tag_id));
CREATE TABLE album_index(id TEXT PRIMARY KEY, title TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE album_asset_index(album_id TEXT NOT NULL REFERENCES album_index(id) ON DELETE CASCADE, asset_id TEXT NOT NULL REFERENCES asset_index(id) ON DELETE CASCADE, position INTEGER NOT NULL, PRIMARY KEY(album_id, asset_id));
CREATE TABLE memory_index(id TEXT PRIMARY KEY, title TEXT NOT NULL, memory_kind TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE memory_asset_index(memory_id TEXT NOT NULL REFERENCES memory_index(id) ON DELETE CASCADE, asset_id TEXT NOT NULL REFERENCES asset_index(id) ON DELETE CASCADE, PRIMARY KEY(memory_id, asset_id));
CREATE TABLE saved_view_index(id TEXT PRIMARY KEY, name TEXT NOT NULL, query_json TEXT NOT NULL, sort_json TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE review_index(id TEXT PRIMARY KEY, candidate_type TEXT NOT NULL, candidate_id TEXT NOT NULL, state TEXT NOT NULL, priority INTEGER NOT NULL DEFAULT 0, revision INTEGER NOT NULL);
CREATE TABLE location_index(id TEXT PRIMARY KEY, asset_id TEXT REFERENCES asset_index(id) ON DELETE CASCADE, latitude REAL NOT NULL, longitude REAL NOT NULL, source TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE ai_task_index(id TEXT PRIMARY KEY, task_kind TEXT NOT NULL, state TEXT NOT NULL, asset_id TEXT REFERENCES asset_index(id), model_id TEXT NOT NULL, input_revision INTEGER NOT NULL, progress REAL NOT NULL DEFAULT 0, revision INTEGER NOT NULL);
CREATE TABLE ai_candidate_index(id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES ai_task_index(id) ON DELETE CASCADE, candidate_type TEXT NOT NULL, state TEXT NOT NULL, payload_json TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE model_component_index(id TEXT PRIMARY KEY, name TEXT NOT NULL, version TEXT NOT NULL, checksum TEXT NOT NULL, licence_status TEXT NOT NULL, compatibility_json TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE operation_index(id TEXT PRIMARY KEY, request_id TEXT NOT NULL UNIQUE, operation_type TEXT NOT NULL, state TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE operation_journal(id INTEGER PRIMARY KEY AUTOINCREMENT, operation_id TEXT NOT NULL REFERENCES operation_index(id) ON DELETE CASCADE, sequence INTEGER NOT NULL, transition TEXT NOT NULL, payload_json TEXT NOT NULL, durable_at TEXT NOT NULL, UNIQUE(operation_id, sequence));
CREATE TABLE recovery_index(id TEXT PRIMARY KEY, operation_id TEXT NOT NULL REFERENCES operation_index(id), recovery_state TEXT NOT NULL, actions_json TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE backup_index(id TEXT PRIMARY KEY, manifest_path TEXT NOT NULL, created_at TEXT NOT NULL, verified_at TEXT, revision INTEGER NOT NULL);
CREATE TABLE restore_index(id TEXT PRIMARY KEY, backup_id TEXT NOT NULL REFERENCES backup_index(id), state TEXT NOT NULL, collision_policy TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE trash_index(id TEXT PRIMARY KEY, asset_identity_id TEXT NOT NULL REFERENCES asset_identity_index(id), original_path TEXT NOT NULL, trash_path TEXT NOT NULL, expires_at TEXT, revision INTEGER NOT NULL);
CREATE TABLE mind_map_node_index(id TEXT PRIMARY KEY, projection_kind TEXT NOT NULL, source_record_id TEXT NOT NULL, label TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE mind_map_edge_index(id TEXT PRIMARY KEY, projection_kind TEXT NOT NULL, source_record_id TEXT NOT NULL, from_node_id TEXT NOT NULL REFERENCES mind_map_node_index(id) ON DELETE CASCADE, to_node_id TEXT NOT NULL REFERENCES mind_map_node_index(id) ON DELETE CASCADE, revision INTEGER NOT NULL);
CREATE TABLE edit_recipe_index(id TEXT PRIMARY KEY, asset_id TEXT NOT NULL REFERENCES asset_index(id), steps_json TEXT NOT NULL, original_revision INTEGER NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE derivative_index(id TEXT PRIMARY KEY, asset_id TEXT NOT NULL REFERENCES asset_index(id), recipe_id TEXT REFERENCES edit_recipe_index(id), path TEXT NOT NULL, content_hash TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE export_index(id TEXT PRIMARY KEY, operation_id TEXT NOT NULL REFERENCES operation_index(id), manifest_path TEXT NOT NULL, state TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE TABLE settings_index(id TEXT PRIMARY KEY CHECK(id='settings'), values_json TEXT NOT NULL, revision INTEGER NOT NULL);
CREATE VIRTUAL TABLE asset_search_fts USING fts5(asset_id UNINDEXED, filename, metadata_text, ocr_text, tags, people, events, tokenize='unicode61');
CREATE INDEX idx_asset_identity_hash ON asset_identity_index(content_hash, hash_algorithm);
CREATE INDEX idx_asset_capture ON asset_index(captured_at DESC, id);
CREATE INDEX idx_asset_root_path ON asset_index(root_id, relative_path);
CREATE INDEX idx_metadata_camera ON metadata_index(camera_make, camera_model);
CREATE INDEX idx_metadata_location ON metadata_index(latitude, longitude);
CREATE INDEX idx_event_range ON event_index(start_at, end_at);
CREATE INDEX idx_event_asset_asset ON event_asset_index(asset_id, event_id);
CREATE INDEX idx_face_asset_status ON face_candidate_index(asset_id, status);
CREATE INDEX idx_face_person_status ON face_candidate_index(person_id, status);
CREATE INDEX idx_membership_person_dates ON group_membership_index(person_id, effective_from, effective_to);
CREATE INDEX idx_relationship_from_type ON relationship_index(from_person_id, relationship_type);
CREATE INDEX idx_relationship_to_type ON relationship_index(to_person_id, relationship_type);
CREATE INDEX idx_tag_parent ON tag_index(parent_tag_id);
CREATE INDEX idx_asset_tag_tag ON asset_tag_index(tag_id, asset_id);
CREATE INDEX idx_album_asset_position ON album_asset_index(album_id, position);
CREATE INDEX idx_review_state_priority ON review_index(state, priority DESC, id);
CREATE INDEX idx_location_lat_lon ON location_index(latitude, longitude);
CREATE INDEX idx_ai_task_state_kind ON ai_task_index(state, task_kind);
CREATE INDEX idx_ai_candidate_state_type ON ai_candidate_index(state, candidate_type);
CREATE INDEX idx_operation_state_updated ON operation_index(state, updated_at);
CREATE INDEX idx_journal_operation_sequence ON operation_journal(operation_id, sequence);
CREATE INDEX idx_recovery_operation ON recovery_index(operation_id, recovery_state);
CREATE INDEX idx_trash_expiry ON trash_index(expires_at);
CREATE INDEX idx_map_node_projection ON mind_map_node_index(projection_kind, source_record_id);
CREATE INDEX idx_map_edge_projection ON mind_map_edge_index(projection_kind, from_node_id, to_node_id);
CREATE INDEX idx_edit_asset ON edit_recipe_index(asset_id, revision);
CREATE INDEX idx_derivative_asset ON derivative_index(asset_id, recipe_id);
INSERT INTO schema_migration(version, applied_at, checksum) VALUES(1, 'PLANNED_AT_RUNTIME', 'GENERATED_FROM_ACTIVE_PLAN');
